advcbv/advcbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app'))
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('detail/<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', views.SchoolDeleteView.as_view(), name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse


# SCHOOL MODEL
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})

# STUDENT MODEL
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import (View,
                                  TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)
from django.http import HttpResponse
from . import models


#BASIC CLASS BASED VIEW
# class CBView(View):
#     def get(self, request):
#         return HttpResponse("CLASS BASED VIEWS ARE COOL!")


# FUNCTION BASED VIEW
# def index(request):
#     return render(request, 'index.html')


#CLASS BASED TEMPLATE VIEW
class IndexView(TemplateView):
    template_name = 'basic_app/basic_app_base.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = 'BASIC INJECTION!'
#         return context


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Basic App Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">School Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'basic_app:list' %}">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item nav-link" href="#">Pricing</a>
          <a class="nav-item nav-link disabled" href="#">Disabled</a>
        </div>
      </div>
    </nav>
    {% block body_block %}
    {% endblock %}
</body>
</html>

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
    <h1>Delete {{ school.name }}</h1>
    <form method="post">
        {% csrf_token %}

        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Welcome to School Detail Page</h1>
        <h2>School Detail:</h2>
        <p>Name: {{ school_detail.name }}</p>
        <p>Principal: {{ school_detail.principal }}</p>
        <p>Location: {{ school_detail.location }}</p>

        <h3>Students: </h3>
        {% for student in school_detail.students.all %}
            <p>{{ student.name }} who is {{ student.age }} years old</p>
        {% endfor %}
    </div>
    
    <div class="container">
        <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
    </div>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}

{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>
{% endblock body_block %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <h1>
    Welcome to a list of all the schools!
    </h1>
    <ol>
        {% for school in schools %}
            <h2><li><a href="{% url 'basic_app:detail' school.id %}">{{ school.name }}</a></li></h2>
        {% endfor %}

    </ol>
{% endblock body_block %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
{#    <nav class="navar navbar-default navbar-static-top">#}
{#        <ul class="nav navbar-nav">#}
{#            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>#}
{#            <li><a class="navbar-link" href="{% url 'index' %}">Admin</a></li>#}
{#            <li></li>#}
{#        </ul>#}
{#    </nav>#}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">School Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'basic_app:list' %}">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url 'admin' %}">Admin</a>
          <a class="nav-item nav-link" href="#">Pricing</a>
          <a class="nav-item nav-link disabled" href="#">Disabled</a>
        </div>
      </div>
    </nav>
    {% block body_block %}
    {% endblock %}
</body>
</html>

advcbv/templates/index.html
{% extends 'base.html' %}

{% block body_block %}
   <div class="jumbotron">
    <h1>
        Home Page!
    </h1>

   </div>
{% endblock body_block %}